{% set name = "ipytest" %}
{% set version = "0.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0aa3cd15d979d2ddc186f8ea184c24083ab7ab020b8fc71a73b2e5ffb5883a47

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - poetry-core
  run:
    - packaging
    - ipython
    - pytest >=5.4
    - python >=3.7

test:
  imports:
    - ipytest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ipytest/
  summary: Unit tests in IPython notebooks.
  description: |
    Sometimes quick experiments in IPython grow large and you find yourself wanting unit tests. This module aims to make testing code in IPython notebooks easy. At its core, it offers a way to run pytest tests inside the notebook environment. It is also designed to make the transfer of the tests into proper python modules easy.
  license: MIT
  license_file: License.md

extra:
  recipe-maintainers:
    - xhochy
    - pmgrafe
