{% set name = "ipytest" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6f1a03b32e243fd331439fcef587b34a72c74aa91e7fb7fa9e0799c83ccbe331

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - packaging
    - ipython
    - pytest >=5.4
    - python >=3.0

test:
  imports:
    - ipytest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ipytest/
  summary: Unit tests in IPython notebooks.
  description: |
    Sometimes quick experiments in IPython grow large and you find yourself wanting unit tests. This module aims to make testing code in IPython notebooks easy. At its core, it offers a way to run pytest tests inside the notebook environment. It is also designed to make the transfer of the tests into proper python modules easy.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - xhochy
    - pmgrafe
