travis:
  secure:
    BINSTAR_TOKEN: noE01IoL/PpD1Z/fVQxxMugIWKUG8menvkyoef+OeHayHrttiky2baRMhHKh9pWaOhQ2I26FW+nBWTK4vED2yq2k+Hm7h6PdaR/iKE95q+SL5mr1f0mdPH90UIbmZusFojGDOV9J5aNXD57Kne2WvbdvbOjvASEAz48/6oLn+o4x4CIOnmVkTYs7RKQvffOtOBD7GNiRw9Xkj+WmIVSe2T6afXAE1PTGaBfm1JzlmRdW49tEuGRyMo6lYE+lGF4TyeAb2t/+6WVhEjLwSGriRvJ8jBsyXdxZ8RrA3TnkRLeZjVWgPm14546xW9xVYx0TVU7GwIJqrtSGNVoR/RQjkemeqBaEV90b4PDKcmm4rzfx3nJ3FW2Ze3nHOgzRgKcQbhkVzy5VcqYEalv3IYXHmYWrH4dv8PJV0zPBPkjE56tFp0AnWMSUIknof09MWnuub9aImVokJ/QD6HsE9ST4PCGx8nwFNXcXujDqMHhoI+oY7eU+YJqnYh9H2p6dS007B/uhrXa2+Zb0p3aid9VniOE5/vOjUzIJnt5Wx2cimLK7GG1/WRzOu9KemT7NMPcwtcLhtMON6ifa2P9QXPWUXF+is9J9QFHstkVvbmJXiz1D0aLG/Ci73X0uRnfNVAwlSQAS7V6DY6C5GyPwklf+iFxeOqT51VCh9rV5VmAJ8Sg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
